"""Business logic services"""

from app.services.audit_service import log_action, get_audit_logs, get_resource_audit_trail
from app.services.entity_access_service import (
    check_entity_access,
    get_user_accessible_entities,
    grant_entity_access,
    revoke_entity_access,
    check_role_permission,
    get_user_roles,
    get_entity_users,
)
from app.services.compliance_engine import (
    calculate_due_date,
    calculate_period_for_frequency,
    generate_instances_for_period,
    calculate_rag_status,
    recalculate_rag_for_tenant,
    check_dependencies_met,
    get_india_fy_quarter,
    get_quarter_end_date,
)
from app.services.workflow_engine import (
    create_workflow_tasks,
    resolve_role_to_user,
    get_tasks_for_instance,
    get_current_task,
    get_next_pending_task,
    start_task,
    complete_task,
    reject_task,
    reassign_task,
    check_instance_completion,
    get_user_assigned_tasks,
    get_overdue_tasks,
    get_tasks_due_soon,
    update_instance_status_from_tasks,
    STANDARD_WORKFLOW,
)
from app.services.evidence_service import (
    upload_evidence_file,
    get_evidence_file_path,
    get_evidence_by_id,
    approve_evidence,
    reject_evidence,
    create_evidence_version,
    delete_evidence,
    get_evidence_for_instance,
    get_evidence_version_history,
    get_pending_approvals,
    check_duplicate_evidence,
    validate_file,
)
from app.services.notification_service import (
    NotificationType,
    create_notification,
    get_user_notifications,
    get_unread_count,
    mark_notification_read,
    mark_all_read,
    delete_notification,
    delete_old_notifications,
    notify_task_assigned,
    notify_task_completed,
    notify_reminder_t3,
    notify_reminder_due,
    notify_overdue_escalation,
    notify_evidence_uploaded,
    notify_evidence_approved,
    notify_evidence_rejected,
    notify_instance_created,
    notify_instance_completed,
)

__all__ = [
    # Audit service
    "log_action",
    "get_audit_logs",
    "get_resource_audit_trail",
    # Entity access service
    "check_entity_access",
    "get_user_accessible_entities",
    "grant_entity_access",
    "revoke_entity_access",
    "check_role_permission",
    "get_user_roles",
    "get_entity_users",
    # Compliance engine
    "calculate_due_date",
    "calculate_period_for_frequency",
    "generate_instances_for_period",
    "calculate_rag_status",
    "recalculate_rag_for_tenant",
    "check_dependencies_met",
    "get_india_fy_quarter",
    "get_quarter_end_date",
    # Workflow engine
    "create_workflow_tasks",
    "resolve_role_to_user",
    "get_tasks_for_instance",
    "get_current_task",
    "get_next_pending_task",
    "start_task",
    "complete_task",
    "reject_task",
    "reassign_task",
    "check_instance_completion",
    "get_user_assigned_tasks",
    "get_overdue_tasks",
    "get_tasks_due_soon",
    "update_instance_status_from_tasks",
    "STANDARD_WORKFLOW",
    # Evidence service
    "upload_evidence_file",
    "get_evidence_file_path",
    "get_evidence_by_id",
    "approve_evidence",
    "reject_evidence",
    "create_evidence_version",
    "delete_evidence",
    "get_evidence_for_instance",
    "get_evidence_version_history",
    "get_pending_approvals",
    "check_duplicate_evidence",
    "validate_file",
    # Notification service
    "NotificationType",
    "create_notification",
    "get_user_notifications",
    "get_unread_count",
    "mark_notification_read",
    "mark_all_read",
    "delete_notification",
    "delete_old_notifications",
    "notify_task_assigned",
    "notify_task_completed",
    "notify_reminder_t3",
    "notify_reminder_due",
    "notify_overdue_escalation",
    "notify_evidence_uploaded",
    "notify_evidence_approved",
    "notify_evidence_rejected",
    "notify_instance_created",
    "notify_instance_completed",
]
