"""Initial schema - all tables

Revision ID: 5f701fd63a5d
Revises:
Create Date: 2025-12-18 09:47:01.028410

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f701fd63a5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("role_code", sa.String(length=50), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_role_code"), "roles", ["role_code"], unique=True)
    op.create_table(
        "tenants",
        sa.Column("tenant_code", sa.String(length=50), nullable=False),
        sa.Column("tenant_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_index(op.f("ix_tenants_tenant_code"), "tenants", ["tenant_code"], unique=True)
    op.create_table(
        "compliance_masters",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("compliance_code", sa.String(length=100), nullable=False),
        sa.Column("compliance_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("sub_category", sa.String(length=100), nullable=True),
        sa.Column("frequency", sa.String(length=50), nullable=False),
        sa.Column("due_date_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_role_code", sa.String(length=50), nullable=True),
        sa.Column("approver_role_code", sa.String(length=50), nullable=True),
        sa.Column("dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("workflow_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("authority", sa.String(length=255), nullable=True),
        sa.Column("penalty_details", sa.Text(), nullable=True),
        sa.Column("reference_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_compliance_masters_tenant_code",
        "compliance_masters",
        ["tenant_id", "compliance_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_compliance_masters_category"), "compliance_masters", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_masters_compliance_code"),
        "compliance_masters",
        ["compliance_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_masters_compliance_name"),
        "compliance_masters",
        ["compliance_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_masters_frequency"), "compliance_masters", ["frequency"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_masters_is_active"), "compliance_masters", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_masters_tenant_id"), "compliance_masters", ["tenant_id"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("entity_code", sa.String(length=50), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("pan", sa.String(length=10), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("cin", sa.String(length=21), nullable=True),
        sa.Column("tan", sa.String(length=10), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("pincode", sa.String(length=10), nullable=True),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_entity_code"), "entities", ["entity_code"], unique=False)
    op.create_index(op.f("ix_entities_entity_name"), "entities", ["entity_name"], unique=False)
    op.create_index(op.f("ix_entities_gstin"), "entities", ["gstin"], unique=False)
    op.create_index(op.f("ix_entities_pan"), "entities", ["pan"], unique=False)
    op.create_index(op.f("ix_entities_status"), "entities", ["status"], unique=False)
    op.create_index(op.f("ix_entities_tenant_id"), "entities", ["tenant_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("tag_name", sa.String(length=100), nullable=False),
        sa.Column("tag_color", sa.String(length=7), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_tag_name"), "tags", ["tag_name"], unique=False)
    op.create_index(op.f("ix_tags_tenant_id"), "tags", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("is_system_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_system_admin"), "users", ["is_system_admin"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_logs_resource",
        "audit_logs",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_tenant_created", "audit_logs", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_audit_logs_user_created", "audit_logs", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_action_type"), "audit_logs", ["action_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "compliance_instances",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("compliance_master_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("rag_status", sa.String(length=10), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("approver_user_id", sa.UUID(), nullable=True),
        sa.Column("blocking_compliance_instance_id", sa.UUID(), nullable=True),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("completion_remarks", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["approver_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["blocking_compliance_instance_id"], ["compliance_instances.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["compliance_master_id"], ["compliance_masters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_compliance_instances_entity_status",
        "compliance_instances",
        ["entity_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "idx_compliance_instances_tenant_status_due",
        "compliance_instances",
        ["tenant_id", "status", "rag_status", "due_date"],
        unique=False,
    )
    op.create_index(
        "idx_compliance_instances_unique",
        "compliance_instances",
        ["compliance_master_id", "entity_id", "period_start", "period_end"],
        unique=True,
    )
    op.create_index(
        op.f("ix_compliance_instances_compliance_master_id"),
        "compliance_instances",
        ["compliance_master_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_due_date"), "compliance_instances", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_instances_entity_id"),
        "compliance_instances",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_owner_user_id"),
        "compliance_instances",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_period_end"),
        "compliance_instances",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_period_start"),
        "compliance_instances",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_rag_status"),
        "compliance_instances",
        ["rag_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_instances_status"), "compliance_instances", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_compliance_instances_tenant_id"),
        "compliance_instances",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "entity_access",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "entity_id"),
    )
    op.create_index(
        op.f("ix_entity_access_tenant_id"), "entity_access", ["tenant_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_user_read",
        "notifications",
        ["user_id", "is_read", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_index(op.f("ix_user_roles_tenant_id"), "user_roles", ["tenant_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("compliance_instance_id", sa.UUID(), nullable=False),
        sa.Column("evidence_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_evidence_id", sa.UUID(), nullable=True),
        sa.Column("approval_status", sa.String(length=50), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_remarks", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["compliance_instance_id"], ["compliance_instances.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["parent_evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_evidence_compliance_status",
        "evidence",
        ["compliance_instance_id", "approval_status"],
        unique=False,
    )
    op.create_index("idx_evidence_hash", "evidence", ["file_hash"], unique=False)
    op.create_index(
        op.f("ix_evidence_approval_status"), "evidence", ["approval_status"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_compliance_instance_id"),
        "evidence",
        ["compliance_instance_id"],
        unique=False,
    )
    op.create_index(op.f("ix_evidence_file_hash"), "evidence", ["file_hash"], unique=False)
    op.create_index(op.f("ix_evidence_tenant_id"), "evidence", ["tenant_id"], unique=False)
    op.create_table(
        "workflow_tasks",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("compliance_instance_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("task_description", sa.Text(), nullable=True),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_role_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.Date(), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("completion_remarks", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assigned_to_role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["assigned_to_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["compliance_instance_id"], ["compliance_instances.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["parent_task_id"], ["workflow_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_workflow_tasks_assigned_user_status",
        "workflow_tasks",
        ["assigned_to_user_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "idx_workflow_tasks_instance_sequence",
        "workflow_tasks",
        ["compliance_instance_id", "sequence_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_assigned_to_user_id"),
        "workflow_tasks",
        ["assigned_to_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_compliance_instance_id"),
        "workflow_tasks",
        ["compliance_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_due_date"), "workflow_tasks", ["due_date"], unique=False
    )
    op.create_index(op.f("ix_workflow_tasks_status"), "workflow_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_workflow_tasks_task_type"), "workflow_tasks", ["task_type"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_tasks_tenant_id"), "workflow_tasks", ["tenant_id"], unique=False
    )
    op.create_table(
        "evidence_tag_mappings",
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_tag_mappings")
    op.drop_index(op.f("ix_workflow_tasks_tenant_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_task_type"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_status"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_due_date"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_compliance_instance_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_assigned_to_user_id"), table_name="workflow_tasks")
    op.drop_index("idx_workflow_tasks_instance_sequence", table_name="workflow_tasks")
    op.drop_index("idx_workflow_tasks_assigned_user_status", table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index(op.f("ix_evidence_tenant_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_file_hash"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_compliance_instance_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_approval_status"), table_name="evidence")
    op.drop_index("idx_evidence_hash", table_name="evidence")
    op.drop_index("idx_evidence_compliance_status", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_user_roles_tenant_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index("idx_notifications_user_read", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_entity_access_tenant_id"), table_name="entity_access")
    op.drop_table("entity_access")
    op.drop_index(op.f("ix_compliance_instances_tenant_id"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_status"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_rag_status"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_period_start"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_period_end"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_owner_user_id"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_entity_id"), table_name="compliance_instances")
    op.drop_index(op.f("ix_compliance_instances_due_date"), table_name="compliance_instances")
    op.drop_index(
        op.f("ix_compliance_instances_compliance_master_id"), table_name="compliance_instances"
    )
    op.drop_index("idx_compliance_instances_unique", table_name="compliance_instances")
    op.drop_index("idx_compliance_instances_tenant_status_due", table_name="compliance_instances")
    op.drop_index("idx_compliance_instances_entity_status", table_name="compliance_instances")
    op.drop_table("compliance_instances")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action_type"), table_name="audit_logs")
    op.drop_index("idx_audit_logs_user_created", table_name="audit_logs")
    op.drop_index("idx_audit_logs_tenant_created", table_name="audit_logs")
    op.drop_index("idx_audit_logs_resource", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_is_system_admin"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tags_tenant_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_tag_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_entities_tenant_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_status"), table_name="entities")
    op.drop_index(op.f("ix_entities_pan"), table_name="entities")
    op.drop_index(op.f("ix_entities_gstin"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_code"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_compliance_masters_tenant_id"), table_name="compliance_masters")
    op.drop_index(op.f("ix_compliance_masters_is_active"), table_name="compliance_masters")
    op.drop_index(op.f("ix_compliance_masters_frequency"), table_name="compliance_masters")
    op.drop_index(op.f("ix_compliance_masters_compliance_name"), table_name="compliance_masters")
    op.drop_index(op.f("ix_compliance_masters_compliance_code"), table_name="compliance_masters")
    op.drop_index(op.f("ix_compliance_masters_category"), table_name="compliance_masters")
    op.drop_index("idx_compliance_masters_tenant_code", table_name="compliance_masters")
    op.drop_table("compliance_masters")
    op.drop_index(op.f("ix_tenants_tenant_code"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_roles_role_code"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
