"""
Seed data for pre-loaded Indian GCC compliance masters
"""

COMPLIANCE_MASTERS_SEED = [
    # ============ GST CATEGORY ============
    {
        "compliance_code": "GSTR-1",
        "compliance_name": "GSTR-1 - Outward Supplies Return",
        "description": "Monthly/quarterly return for reporting outward supplies (sales)",
        "category": "GST",
        "sub_category": "GST Returns",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 11, "offset_days": 0},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,  # Use standard workflow
        "is_active": True,
        "is_template": True,
        "authority": "CBIC (Central Board of Indirect Taxes and Customs)",
        "penalty_details": "Late fee of Rs. 50 per day (Rs. 20 if nil return). Maximum Rs. 5,000",
        "reference_links": ["https://www.gst.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "filing_mode": "online"},
    },
    {
        "compliance_code": "GSTR-3B",
        "compliance_name": "GSTR-3B - Summary Return",
        "description": "Monthly summary return for reporting tax liability and ITC",
        "category": "GST",
        "sub_category": "GST Returns",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 20, "offset_days": 0},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "CBIC",
        "penalty_details": "Late fee of Rs. 50 per day (Rs. 20 if nil return). Interest @ 18% p.a. on tax payable",
        "reference_links": ["https://www.gst.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "filing_mode": "online"},
    },
    {
        "compliance_code": "GSTR-9",
        "compliance_name": "GSTR-9 - Annual Return",
        "description": "Annual return consolidating all monthly/quarterly returns",
        "category": "GST",
        "sub_category": "GST Returns",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 12, "day": 31, "offset_days": 0},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "CBIC",
        "penalty_details": "Late fee of Rs. 200 per day (Rs. 100 for nil filers). Maximum Rs. 10,000",
        "reference_links": ["https://www.gst.gov.in/"],
        "meta_data": {"compliance_type": "annual", "filing_mode": "online"},
    },
    {
        "compliance_code": "GSTR-9C",
        "compliance_name": "GSTR-9C - Reconciliation Statement",
        "description": "Reconciliation statement certified by CA/CMA (for turnover > 5 Cr)",
        "category": "GST",
        "sub_category": "GST Returns",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 12, "day": 31, "offset_days": 0},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": ["GSTR-9"],
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "CBIC",
        "penalty_details": "No specific penalty, but non-filing may lead to scrutiny",
        "reference_links": ["https://www.gst.gov.in/"],
        "meta_data": {"compliance_type": "annual", "requires_certification": True},
    },
    # ============ DIRECT TAX CATEGORY ============
    {
        "compliance_code": "TDS-PAY-MONTHLY",
        "compliance_name": "TDS Payment - Monthly",
        "description": "Monthly TDS payment to government",
        "category": "Direct Tax",
        "sub_category": "TDS",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 7, "offset_days": 0},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Interest @ 1.5% per month for delay. Penalty up to TDS amount",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "payment_mode": "online"},
    },
    {
        "compliance_code": "TDS-Q1",
        "compliance_name": "TDS Return - Q1 (Apr-Jun)",
        "description": "Quarterly TDS return for Q1",
        "category": "Direct Tax",
        "sub_category": "TDS",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "quarterly", "offset_days": 31},  # 31 days after quarter end
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Late fee of Rs. 200 per day. Maximum penalty equal to TDS amount",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "quarter": 1},
    },
    {
        "compliance_code": "TDS-Q2",
        "compliance_name": "TDS Return - Q2 (Jul-Sep)",
        "description": "Quarterly TDS return for Q2",
        "category": "Direct Tax",
        "sub_category": "TDS",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "quarterly", "offset_days": 31},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Late fee of Rs. 200 per day. Maximum penalty equal to TDS amount",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "quarter": 2},
    },
    {
        "compliance_code": "TDS-Q3",
        "compliance_name": "TDS Return - Q3 (Oct-Dec)",
        "description": "Quarterly TDS return for Q3",
        "category": "Direct Tax",
        "sub_category": "TDS",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "quarterly", "offset_days": 31},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Late fee of Rs. 200 per day. Maximum penalty equal to TDS amount",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "quarter": 3},
    },
    {
        "compliance_code": "TDS-Q4",
        "compliance_name": "TDS Return - Q4 (Jan-Mar)",
        "description": "Quarterly TDS return for Q4",
        "category": "Direct Tax",
        "sub_category": "TDS",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "quarterly", "offset_days": 31},
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Late fee of Rs. 200 per day. Maximum penalty equal to TDS amount",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "periodic", "quarter": 4},
    },
    {
        "compliance_code": "ADV-TAX-Q1",
        "compliance_name": "Advance Tax Payment - Q1",
        "description": "First installment of advance tax (15% of tax liability)",
        "category": "Direct Tax",
        "sub_category": "Advance Tax",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "fixed_date", "month": 6, "day": 15},  # June 15
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Interest @ 1% per month for shortfall",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "payment", "installment": 1, "percentage": 15},
    },
    {
        "compliance_code": "ITR-CORP",
        "compliance_name": "Corporate Income Tax Return",
        "description": "Annual income tax return filing for companies",
        "category": "Direct Tax",
        "sub_category": "Income Tax",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 9, "day": 30, "offset_days": 0},  # Sept 30
        "owner_role_code": "TAX_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Late fee up to Rs. 10,000. Interest @ 1% per month on unpaid tax",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "annual", "form_type": "ITR-6"},
    },
    # ============ PAYROLL CATEGORY ============
    {
        "compliance_code": "PF-PAY",
        "compliance_name": "PF Payment - Monthly",
        "description": "Monthly EPF & EPS payment",
        "category": "Payroll",
        "sub_category": "PF",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 15, "offset_days": 0},
        "owner_role_code": "HR_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "EPFO (Employees' Provident Fund Organisation)",
        "penalty_details": "Damages @ 12% p.a. for delay up to 2 months, 25% for longer delays",
        "reference_links": ["https://www.epfindia.gov.in/"],
        "meta_data": {"compliance_type": "payment"},
    },
    {
        "compliance_code": "ESI-PAY",
        "compliance_name": "ESI Payment - Monthly",
        "description": "Monthly ESIC payment",
        "category": "Payroll",
        "sub_category": "ESI",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 15, "offset_days": 0},
        "owner_role_code": "HR_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "ESIC (Employees' State Insurance Corporation)",
        "penalty_details": "Interest @ 12% p.a. for delay. Penalty up to contribution amount",
        "reference_links": ["https://www.esic.in/"],
        "meta_data": {"compliance_type": "payment"},
    },
    {
        "compliance_code": "PT-PAY",
        "compliance_name": "Professional Tax - Monthly",
        "description": "Monthly professional tax payment (state-specific)",
        "category": "Payroll",
        "sub_category": "Professional Tax",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 30, "offset_days": 0},
        "owner_role_code": "HR_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "State Commercial Tax Department",
        "penalty_details": "Varies by state. Generally interest and penalty for delay",
        "reference_links": None,
        "meta_data": {"compliance_type": "payment", "state_specific": True},
    },
    {
        "compliance_code": "FORM16-ISSUE",
        "compliance_name": "Form 16 Issuance",
        "description": "Annual TDS certificate issuance to employees",
        "category": "Payroll",
        "sub_category": "TDS Certificates",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 6, "day": 15, "offset_days": 0},  # June 15
        "owner_role_code": "HR_LEAD",
        "approver_role_code": "CFO",
        "dependencies": ["TDS-Q4"],
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Income Tax Department",
        "penalty_details": "Penalty of Rs. 100 per day for delay per employee",
        "reference_links": ["https://www.incometax.gov.in/"],
        "meta_data": {"compliance_type": "certificate"},
    },
    # ============ MCA CATEGORY ============
    {
        "compliance_code": "DIR3-KYC",
        "compliance_name": "DIR-3 KYC - Director KYC",
        "description": "Annual KYC for directors with MCA",
        "category": "MCA",
        "sub_category": "Director Related",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 9, "day": 30, "offset_days": 0},
        "owner_role_code": "COMPANY_SECRETARY",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "MCA (Ministry of Corporate Affairs)",
        "penalty_details": "DIN gets deactivated if not filed. Rs. 5,000 penalty for filing after due date",
        "reference_links": ["https://www.mca.gov.in/"],
        "meta_data": {"compliance_type": "annual"},
    },
    {
        "compliance_code": "AOC4",
        "compliance_name": "AOC-4 - Annual Financials Filing",
        "description": "Filing of annual financial statements with ROC",
        "category": "MCA",
        "sub_category": "Annual Filings",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 9, "day": 30, "offset_days": 0},
        "owner_role_code": "COMPANY_SECRETARY",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "MCA",
        "penalty_details": "Rs. 100 per day of delay. Additional penalty of Rs. 100 per day to every officer",
        "reference_links": ["https://www.mca.gov.in/"],
        "meta_data": {"compliance_type": "annual"},
    },
    {
        "compliance_code": "MGT7",
        "compliance_name": "MGT-7 - Annual Return",
        "description": "Annual return filing with ROC",
        "category": "MCA",
        "sub_category": "Annual Filings",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 12, "day": 28, "offset_days": 0},
        "owner_role_code": "COMPANY_SECRETARY",
        "approver_role_code": "CFO",
        "dependencies": ["AOC4"],
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "MCA",
        "penalty_details": "Rs. 100 per day of delay. Additional penalty to officers",
        "reference_links": ["https://www.mca.gov.in/"],
        "meta_data": {"compliance_type": "annual"},
    },
    # ============ FEMA CATEGORY ============
    {
        "compliance_code": "FCGPR",
        "compliance_name": "FC-GPR - Foreign Investment Reporting",
        "description": "Reporting of foreign investment to RBI",
        "category": "FEMA",
        "sub_category": "FDI Reporting",
        "frequency": "Event-based",
        "due_date_rule": {"type": "event_based", "offset_days": 30},  # Within 30 days of event
        "owner_role_code": "CFO",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "RBI (Reserve Bank of India)",
        "penalty_details": "Compounding fee for delay as per RBI guidelines",
        "reference_links": ["https://www.rbi.org.in/"],
        "meta_data": {"compliance_type": "event_based"},
    },
    {
        "compliance_code": "ODI-APR",
        "compliance_name": "ODI Annual Return",
        "description": "Annual return for Overseas Direct Investment",
        "category": "FEMA",
        "sub_category": "ODI Reporting",
        "frequency": "Annual",
        "due_date_rule": {"type": "annual", "month": 6, "day": 15, "offset_days": 0},
        "owner_role_code": "CFO",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "RBI",
        "penalty_details": "Compounding fee for delay",
        "reference_links": ["https://www.rbi.org.in/"],
        "meta_data": {"compliance_type": "annual"},
    },
    # ============ FP&A CATEGORY ============
    {
        "compliance_code": "MONTHLY-MIS",
        "compliance_name": "Monthly MIS Reporting",
        "description": "Monthly management information system report preparation",
        "category": "FP&A",
        "sub_category": "Internal Reporting",
        "frequency": "Monthly",
        "due_date_rule": {"type": "monthly", "day": 5, "offset_days": 0},
        "owner_role_code": "FPA_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Internal",
        "penalty_details": "Internal deadline",
        "reference_links": None,
        "meta_data": {"compliance_type": "internal"},
    },
    {
        "compliance_code": "QUARTERLY-FORECAST",
        "compliance_name": "Quarterly Financial Forecast",
        "description": "Quarterly financial forecast and variance analysis",
        "category": "FP&A",
        "sub_category": "Internal Reporting",
        "frequency": "Quarterly",
        "due_date_rule": {"type": "quarterly", "offset_days": 15},
        "owner_role_code": "FPA_LEAD",
        "approver_role_code": "CFO",
        "dependencies": None,
        "workflow_config": None,
        "is_active": True,
        "is_template": True,
        "authority": "Internal",
        "penalty_details": "Internal deadline",
        "reference_links": None,
        "meta_data": {"compliance_type": "internal"},
    },
]
